# Site settings
domain: "2RD.top"
title: "2RD Channel | Linktree"
description: "รวมลิงค์โปรไฟล์โซเชียลมีเดียทั้งหมดของผม"
page_404: "404 PAGE NOT FOUND"
page_404_description: "ไซต์ที่กําหนดค่าตามที่อยู่นี้ไม่ มีไฟล์ที่ร้องขอ"

# User settings
username: "2RD Channel"
user_description: ""
footer: "&copy;2025"
email: "contact@2rd.top"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
